### ISSUE TITLE
Hello, do you have a related paper?

### ISSUE THREAD

**Issue by skyknights** [anhtuanhsgs/MedicalRl#1]

**Comment by anhtuanhsgs** [comment]
Hi, 
Thanks for the interest. Here are some of our published papers for using deep reinforcement learning for medical images: 

[ColorRL: Reinforced Coloring for End-to-End Instance Segmentation](https://openaccess.thecvf.com/content/CVPR2021/papers/Tuan_ColorRL_Reinforced_Coloring_for_End-to-End_Instance_Segmentation_CVPR_2021_paper.pdf) (CVPR2021) | [code](https://github.com/anhtuanhsgs/ColorRL)

[RLCorrector: Reinforced Proofreading for Cell-level Microscopy Image Segmentation](https://arxiv.org/abs/2106.05487) (Arxiv preprint) | [code](https://github.com/hvcl/RLCorrector_and_Segmentation)
